"""sensor_readings

Revision ID: e720c9cb0a1c
Revises: 88d01720cb29
Create Date: 2026-10-06 09:26:59.347340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e720c9cb0a1c'
down_revision: Union[str, Sequence[str], None] = '88d01720cb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_readings_device_id_recorded_at', 'sensor_readings', ['device_id', 'recorded_at'], unique=False)
    op.add_column('devices', sa.Column('sampling_interval_seconds', sa.Integer(), server_default='300', nullable=False))
    op.add_column('devices', sa.Column('tracking_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###
    # Promote sampling interval from default_config JSON to the new column (min 5)
    op.execute("""
        UPDATE devices
        SET sampling_interval_seconds =
            GREATEST((default_config->>'sampling_interval_seconds')::int, 5)
        WHERE default_config->>'sampling_interval_seconds' ~ '^[0-9]{1,6}$'
    """)

    # Phase 5 protocol values for sensors: simulation family -> simulation, edge -> mqtt
    op.execute("""
        UPDATE devices
        SET default_config = jsonb_set(default_config, '{protocol}', '"simulation"')
        WHERE role = 'sensor' AND device_family = 'simulation'
          AND (default_config->>'protocol' IS NULL OR default_config->>'protocol' = 'sim')
    """)
    op.execute("""
        UPDATE devices
        SET default_config = jsonb_set(default_config, '{protocol}', '"mqtt"')
        WHERE role = 'sensor' AND device_family = 'edge'
          AND (default_config->>'protocol' IS NULL OR default_config->>'protocol' = 'gpio-stub')
    """)


def downgrade() -> None:
   """Downgrade schema."""
   op.drop_column('devices', 'tracking_enabled')
   op.drop_column('devices', 'sampling_interval_seconds')
   op.drop_index('ix_sensor_readings_device_id_recorded_at', table_name='sensor_readings')
   op.drop_table('sensor_readings')